#!/bin/bash

# set -e ## error
set -x

yarn run build-minify

git add .
git commit -m 'autocommit'
git push

ssh do2 "cd /mnt/volume_sfo2_01/projects/docker/volumes/piousbox_drupal_production_data/web/themes/piousbox_drupal_theme ; git pull && echo $HOSTNAME ok"


set +e
set +x
echo ok
